[mcp_servers.index_mcp]
command = "/Users/mohammedsayf/Desktop/index-mcp/start.sh"
startup_timeout_sec = 30
tool_timeout_sec = 300

[mcp_servers.index_mcp.env]
INDEX_MCP_LOG_LEVEL = "INFO"
INDEX_MCP_WORKING_DIR = "/Users/mohammedsayf/Desktop/index-mcp"
INDEX_MCP_DATABASE_NAME = ".mcp-index.sqlite"
