/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NativeEmbeddingRequest {
  texts: Array<string>
  model?: string
  batchSize?: number
}
export declare function generateEmbeddings(request: NativeEmbeddingRequest): Array<Float32Array>
export declare function clearEmbeddingCache(): void
export interface ScanOptions {
  root: string
  include: Array<string>
  exclude: Array<string>
  maxFileSizeBytes?: number
  needsContent: boolean
}
export interface MetadataOptions {
  root: string
  include: Array<string>
  exclude: Array<string>
  maxFileSizeBytes?: number
}
export interface ReadRepoOptions {
  root: string
  paths: Array<string>
  maxFileSizeBytes?: number
  needsContent: boolean
}
export interface NativeFileEntry {
  path: string
  size: number
  modified: number
  hash: string
  content?: string
  isBinary: boolean
}
export interface NativeMetadataEntry {
  path: string
  size: number
  modified: number
}
export interface NativeSkippedFile {
  path: string
  reason: string
  size?: number
  message?: string
}
export interface NativeScanResult {
  files: Array<NativeFileEntry>
  skipped: Array<NativeSkippedFile>
}
export interface NativeMetadataResult {
  entries: Array<NativeMetadataEntry>
  skipped: Array<NativeSkippedFile>
}
export interface NativeReadResult {
  files: Array<NativeFileEntry>
  skipped: Array<NativeSkippedFile>
}
export interface NativeChunkFragment {
  content: string
  byteStart: number
  byteEnd: number
  lineStart: number
  lineEnd: number
}
export interface AnalyzeOptions {
  path: string
  content: string
  chunkSizeTokens?: number
  chunkOverlapTokens?: number
}
export interface NativeAnalysisResult {
  chunks: Array<NativeChunkFragment>
}
export interface BatchAnalyzeFileRequest {
  path: string
  content: string
}
export interface BatchAnalyzeOptions {
  files: Array<BatchAnalyzeFileRequest>
  chunkSizeTokens?: number
  chunkOverlapTokens?: number
}
export interface NativeBatchAnalysisFile {
  path: string
  chunks: Array<NativeChunkFragment>
}
export interface NativeBatchAnalysisResult {
  files: Array<NativeBatchAnalysisFile>
}
export declare function scanRepo(options: ScanOptions): NativeScanResult
export declare function scanRepoMetadata(options: MetadataOptions): NativeMetadataResult
export declare function readRepoFiles(options: ReadRepoOptions): NativeReadResult
export declare function analyzeFileContent(options: AnalyzeOptions): NativeAnalysisResult
export declare function analyzeFileContentBatch(options: BatchAnalyzeOptions): NativeBatchAnalysisResult
