/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ScanOptions {
  root: string
  include: Array<string>
  exclude: Array<string>
  maxFileSizeBytes?: number
  needsContent: boolean
}
export interface NativeFileEntry {
  path: string
  size: number
  modified: number
  hash: string
  content?: string
  isBinary: boolean
}
export interface NativeSkippedFile {
  path: string
  reason: string
  size?: number
  message?: string
}
export interface NativeScanResult {
  files: Array<NativeFileEntry>
  skipped: Array<NativeSkippedFile>
}
export declare function scanRepo(options: ScanOptions): NativeScanResult
