/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ScanOptions {
  root: string
  include: Array<string>
  exclude: Array<string>
  maxFileSizeBytes?: number
  needsContent: boolean
}
export interface MetadataOptions {
  root: string
  include: Array<string>
  exclude: Array<string>
  maxFileSizeBytes?: number
}
export interface ReadRepoOptions {
  root: string
  paths: Array<string>
  maxFileSizeBytes?: number
  needsContent: boolean
}
export interface NativeFileEntry {
  path: string
  size: number
  modified: number
  hash: string
  content?: string
  isBinary: boolean
}
export interface NativeMetadataEntry {
  path: string
  size: number
  modified: number
}
export interface NativeSkippedFile {
  path: string
  reason: string
  size?: number
  message?: string
}
export interface NativeScanResult {
  files: Array<NativeFileEntry>
  skipped: Array<NativeSkippedFile>
}
export interface NativeMetadataResult {
  entries: Array<NativeMetadataEntry>
  skipped: Array<NativeSkippedFile>
}
export interface NativeReadResult {
  files: Array<NativeFileEntry>
  skipped: Array<NativeSkippedFile>
}
export interface NativeChunkFragment {
  content: string
  byteStart: number
  byteEnd: number
  lineStart: number
  lineEnd: number
}
export interface AnalyzeOptions {
  path: string
  content: string
  chunkSizeTokens?: number
  chunkOverlapTokens?: number
}
export interface NativeAnalysisResult {
  chunks: Array<NativeChunkFragment>
}
export declare function scanRepo(options: ScanOptions): NativeScanResult
export declare function scanRepoMetadata(options: MetadataOptions): NativeMetadataResult
export declare function readRepoFiles(options: ReadRepoOptions): NativeReadResult
export declare function analyzeFileContent(options: AnalyzeOptions): NativeAnalysisResult
